# Generated by Django 5.2.6 on 2025-09-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, ist die Veranstaltung für alle offen und benötigt Datenschutzerklärung', verbose_name='Öffentlich zugänglich'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Leer lassen für unbegrenzte Teilnehmer', null=True, verbose_name='Maximale Teilnehmerzahl'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird ein Anmeldeformular angezeigt', verbose_name='Anmeldung erforderlich'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Nachricht/Anmerkungen')),
                ('privacy_consent', models.BooleanField(help_text='Einverständnis zur Datenschutzerklärung', verbose_name='Datenschutz zugestimmt')),
                ('newsletter_consent', models.BooleanField(default=False, help_text='Möchte Newsletter erhalten', verbose_name='Newsletter-Anmeldung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Bestätigt')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Veranstaltungsanmeldung',
                'verbose_name_plural': 'Veranstaltungsanmeldungen',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
