# Generated by Django 5.2.6 on 2025-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_is_public_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='photo_consent',
            field=models.BooleanField(default=False, help_text='Einverständnis zur Anfertigung und Veröffentlichung von Fotos', verbose_name='Fotoerlaubnis'),
        ),
    ]
