# Generated by Django 5.2.6 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eventregistration_photo_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('primary', 'Kulturelle Veranstaltungen'), ('secondary', 'Workshops & Seminare'), ('success', 'Integrationsprojekte'), ('accent', 'Sprachkurse'), ('purple', 'Begegnungen'), ('orange', 'Feste & Feiern')], default='primary', help_text='Wählen Sie die Kategorie zur Farbkodierung im Kalender', max_length=20, verbose_name='Kategorie'),
        ),
    ]
