# Generated by Django 5.2.6 on 2025-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Beantwortet'),
        ),
    ]
