# Generated by Django 5.2.6 on 2025-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact_is_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('general', 'Allgemeine Dokumente'), ('forms', 'Formulare'), ('brochures', 'Broschüren'), ('reports', 'Berichte'), ('guidelines', 'Richtlinien'), ('certificates', 'Zertifikate'), ('other', 'Sonstiges')], default='general', max_length=20, verbose_name='Kategorie')),
                ('file', models.FileField(help_text='Unterstützte Formate: PDF, DOC, DOCX, XLS, XLSX, PPT, PPTX, TXT, RTF', upload_to='documents/', verbose_name='Datei')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hervorgehoben')),
                ('is_public', models.BooleanField(default=True, verbose_name='Öffentlich zugänglich')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Downloads')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-created_at'],
            },
        ),
    ]
