# Generated by Django 5.2.6 on 2025-11-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('participant_number', models.CharField(help_text='Eindeutige Nummer für den Teilnehmer', max_length=20, unique=True, verbose_name='Teilnehmernummer')),
                ('event_title', models.CharField(max_length=200, verbose_name='Veranstaltungstitel')),
                ('completion_date', models.DateField(verbose_name='Abschlussdatum')),
                ('certificate_file', models.FileField(help_text='PDF-Datei des Zertifikats', upload_to='certificates/', verbose_name='Zertifikat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zertifikat',
                'verbose_name_plural': 'Zertifikate',
                'ordering': ['-completion_date', 'last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'Alle Dokumente'), ('forms', 'Formulare'), ('brochures', 'Broschüren'), ('reports', 'Berichte'), ('certificates', 'Zertifikate')], default='general', max_length=20, verbose_name='Kategorie'),
        ),
    ]
