# Generated by Django 5.2.6 on 2025-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='Einverständnis zur Datenschutzerklärung', verbose_name='Datenschutz zugestimmt'),
        ),
    ]
