# Generated by Django 5.2.6 on 2025-11-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_eventregistration_privacy_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_only',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, ist ein Einladungscode für die Anmeldung erforderlich', verbose_name='Nur mit Einladung'),
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code für diese Einladung (z.B. IFTAR2024-AHMED)', max_length=50, unique=True, verbose_name='Einladungscode')),
                ('invited_name', models.CharField(help_text='Name der eingeladenen Person (optional, nur zur Erinnerung)', max_length=200, verbose_name='Name des Eingeladenen')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Wie oft dieser Code verwendet werden kann', verbose_name='Maximale Nutzungen')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Bereits verwendet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leer lassen für unbegrenzte Gültigkeit', null=True, verbose_name='Gültig bis')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen zu dieser Einladung', verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='main.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Einladungscode',
                'verbose_name_plural': 'Einladungscodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='invitation_code',
            field=models.ForeignKey(blank=True, help_text='Falls mit Einladungscode angemeldet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='main.invitationcode', verbose_name='Einladungscode'),
        ),
    ]
