# Generated by Django 5.2.6 on 2025-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_invitation_only_invitationcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('message', models.TextField(help_text='Haupttext der Ankündigung', verbose_name='Nachricht')),
                ('announcement_type', models.CharField(choices=[('event', 'Wichtiges Ereignis'), ('invitation', 'Einladung'), ('funeral', 'Traueranzeige'), ('news', 'Wichtige Nachricht'), ('warning', 'Warnung')], default='news', max_length=20, verbose_name='Typ')),
                ('image', models.ImageField(blank=True, help_text='Optionales Bild für die Ankündigung', null=True, upload_to='announcements/', verbose_name='Bild')),
                ('background_music', models.FileField(blank=True, help_text='Optionale Audiodatei (MP3, WAV)', null=True, upload_to='announcements/audio/', verbose_name='Hintergrundmusik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('start_date', models.DateTimeField(help_text='Ab wann soll die Ankündigung angezeigt werden?', verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(help_text='Bis wann soll die Ankündigung angezeigt werden?', verbose_name='Enddatum')),
                ('auto_close_seconds', models.PositiveIntegerField(default=10, help_text='Nach wie vielen Sekunden soll das Pop-up automatisch schließen? (0 = nie)', verbose_name='Automatisches Schließen (Sekunden)')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex-Farbe (z.B. #ffffff)', max_length=7, verbose_name='Hintergrundfarbe')),
                ('text_color', models.CharField(default='#000000', help_text='Hex-Farbe (z.B. #000000)', max_length=7, verbose_name='Textfarbe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ankündigung',
                'verbose_name_plural': 'Ankündigungen',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(help_text='Eindeutiger Code für diese Einladung (nur Großbuchstaben A-Z, Zahlen 0-9 und Bindestrich)', max_length=50, unique=True, verbose_name='Einladungscode'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='invited_name',
            field=models.CharField(blank=True, help_text='Name der eingeladenen Person (optional, nur zur Erinnerung)', max_length=200, verbose_name='Name des Eingeladenen'),
        ),
    ]
